// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXNcLpXKkucyNKQnfUQnRL3F2O86utaYQ',
    appId: '1:553006201316:web:acdcc70b9214b2d4056ff1',
    messagingSenderId: '553006201316',
    projectId: 'eddyyy261203',
    authDomain: 'eddyyy261203.firebaseapp.com',
    storageBucket: 'eddyyy261203.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6wtTTKhCMEw24Q-S0__c3khWKHBNt1xY',
    appId: '1:553006201316:android:6051c7335f629508056ff1',
    messagingSenderId: '553006201316',
    projectId: 'eddyyy261203',
    storageBucket: 'eddyyy261203.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXFwouVh0Zah463kURmIfmmUsODE6MT74',
    appId: '1:553006201316:ios:5b24e1fe4d1f106a056ff1',
    messagingSenderId: '553006201316',
    projectId: 'eddyyy261203',
    storageBucket: 'eddyyy261203.appspot.com',
    iosBundleId: 'com.example.instagramCloneFlutter',
  );
}
